version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lds3-pedro-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meritocracy
    volumes:
      - ./database:/var/lib/mysql

volumes:
  db_data:
    driver: local